#!/usr/bin/env python
import os
import sys

os.environ['DJANGO_SETTINGS_MODULE'] = 'webfaf.settings'
virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except:
    pass

import django.core.handlers.wsgi

# This is required to load libsatyr.so correctly
# OpenShift does not seem to provide any writable library path
# and LD_LIBRARY_PATH env variable is already stolen by PostgreSQL
os.chdir(os.path.join(os.environ["OPENSHIFT_FAF_ROOT"], "usr", "lib64"))

application = django.core.handlers.wsgi.WSGIHandler()
